version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: construction_transport_server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    working_dir: /app

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: construction_transport_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_secret
      POSTGRES_DB: construction_transport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
